unprivileged_user: nfsuser
timezone: "Europe/Berlin"

host:
  name: yourhostname
  private_ip: "local_ip_in_virtual_switch"

domains: []

ssh:
  user_name: sshname
  host_name: "same as host.name"
  public_key_to_add: "ssh-ed25519 yourpublickey"
qbittorrent:
  # sabnzbd uses the default port
  webui_port: 8081
  torrenting_port: 6881
  password_hash: "@ByteArray(usernamehash:passwordhash)"
  upload_limit_kb: 512000
qui:
  host: "192.168.100.2"
  port: 7476
tailscale_auth_key: "tskey-auth-..."
nftables:
  whitelisted_sources:
    # qbittorrent
    - dport: "8081"
      saddr: "192.168.100.0/24"
      protocol: tcp
    # qui (optional)
    - dport: "7476"
      saddr: "192.168.100.0/24"
      protocol: tcp
    # sabnzbd
    - dport: "8080"
      saddr: "192.168.100.0/24"
      protocol: tcp
    # tdarr
    - dport: "8265"
      saddr: "192.168.100.0/24"
      protocol: tcp
      # nfs
    - dport: "2049"
      saddr: "192.168.100.0/24"
      protocol: tcp
    - dport: "2049"
      saddr: "192.168.100.0/24"
      protocol: udp
      # portmap
    - dport: "111"
      saddr: "192.168.100.0/24"
      protocol: udp
      # netdata
    - dport: "19999"
      saddr: "192.168.100.0/24"
      protocol: tcp
  whitelisted_ports:
    - "22"
    # qbittorrent
    - "6881"
nat:
  enabled: false
